name: Host Static Site to AWS S3
run-name: "ðŸš€ Deployment by ${{ github.actor }} on branch ${{ github.ref_name }}"

on:
  push:
    branches:
      - main   # ONLY main will deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-south-1
      S3_BUCKET: admin-dashboard-site-prod
      CUSTOM_DOMAIN: admin.epielio.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS IAM credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: ðŸ§¹ Clean S3 Bucket Before Deploy
        run: |
          echo "Cleaning bucket: $S3_BUCKET"
          aws s3 rm s3://$S3_BUCKET --recursive

      - name: ðŸ”„ Sync ONLY Required Files to S3
        run: |
          echo "Deploying only static site files"

          # Upload folders
          aws s3 sync assets/ s3://$S3_BUCKET/assets/ --delete
          aws s3 sync pages/ s3://$S3_BUCKET/pages/ --delete

          # Upload HTML files in root
          for file in *.html *.txt; do
            if [ -f "$file" ]; then
              aws s3 cp "$file" s3://$S3_BUCKET/
            fi
          done

      - name: ðŸš€ Invalidate CloudFront Cache
        run: |
          DIST_ID="${{ secrets.CF_PROD }}"
          echo "Invalidating CloudFront Distribution: $DIST_ID"
          aws cloudfront create-invalidation \
            --distribution-id "$DIST_ID" \
            --paths "/*"

      - name: ðŸŒ Print Website URL
        run: |
          echo "-----------------------------------"
          echo "Deployment completed successfully!"
          echo "S3 Bucket: $S3_BUCKET"
          echo "CloudFront: https://${CUSTOM_DOMAIN}"
          echo "-----------------------------------"

      - name: ðŸ§¾ Add summary with clickable links
        if: success()
        run: |
          
          echo "## âœ… Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** $ENVIRONMENT" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "**S3 Static Website URL:**" >> $GITHUB_STEP_SUMMARY
          echo "http://$S3_BUCKET.s3-website.$AWS_REGION.amazonaws.com" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "**Custom Domain:**" >> $GITHUB_STEP_SUMMARY
          echo "http://${CUSTOM_DOMAIN}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "ðŸš€ Deployment successful!" >> $GITHUB_STEP_SUMMARY

